# Generated by Django 5.1.7 on 2025-04-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_content_remove_recipe_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quanity',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
